---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: snipeit
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: $(OIDC_ARN)
